name: Publicar Motivación

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Ejecución a las 8:00 AM y 6:00 PM CDMX aprox
    - cron: '0 14,0 * * *'

jobs:
  generar-imagen:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias directamente
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu
          python -m pip install --upgrade pip
          pip install requests Pillow deep_translator

      - name: Crear y Enviar Arte
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python main.py
