name: Publicar Motivación

on:
  push:
  workflow_dispatch:
  schedule:
    # 8:00 AM y 6:00 PM (Hora CDMX aprox)
    - cron: '0 14,0 * * *'

jobs:
  generar-imagen:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu
          pip install -r requirements.txt

      - name: Crear y Enviar Arte
        env:
          # Estas ya las tenías:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          # --- ESTAS SON LAS NUEVAS QUE FALTABAN ---
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python main.py
