name: Publicar Motivación

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Ejecución a las 8:00 AM y 6:00 PM CDMX aprox (14:00 y 00:00 UTC)
    - cron: '0 14,0 * * *'

jobs:
  generar-imagen:
    runs-on: ubuntu-latest
    # Permisos necesarios para que el bot pueda subir el historial.txt actualizado
    permissions:
      contents: write

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias y fuentes
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu fonts-liberation
          python -m pip install --upgrade pip
          # [cite_start]Instalación de librerías del proyecto [cite: 1]
          pip install requests Pillow deep_translator numpy

      - name: Crear y Enviar Arte
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python main.py

      - name: Guardar Historial de frases
        run: |
          git config --global user.name "JJMex-Bot"
          git config --global user.email "bot@jjmex.com"
          git add historial.txt
          # Solo hace commit y push si el archivo historial.txt cambió
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizar historial de frases [Skip CI]" && git push)
